# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[tool.bumpversion]
current_version = "0.4.0"

[[tool.bumpversion.files]]
glob = "docs/man/man1/*.1.adoc"

[[tool.bumpversion.files]]
filename = "src/lib.rs"
