[package]
name = "hf"
version = "0.1.0"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2021"
rust-version = "1.56.0"
description = "An utility for hidden file/directory"
readme = "README.md"
repository = "https://github.com/sorairolake/hf"
license = "Apache-2.0 OR MIT"
keywords = ["hidden"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
