[package]
name = "hf"
version = "0.2.1"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2021"
rust-version = "1.61.0"
description = "An utility for hidden file/directory"
readme = "README.md"
repository = "https://github.com/sorairolake/hf"
license = "Apache-2.0 OR MIT"
keywords = ["hidden"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
clap = { version = "3.2.21", features = ["derive"] }
clap_complete = "3.2.5"
log = "0.4.17"
simplelog = "0.12.0"
sysexits = "0.3.1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.38.0", features = ["alloc", "Win32_Foundation", "Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile = "3.3.0"

[profile.release]
lto = true
strip = true
