# SPDX-FileCopyrightText: 2022 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "hf"
version = "0.3.2"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2021"
rust-version = "1.74.0"
description = "Cross-platform hidden file library and utility"
documentation = "https://docs.rs/hf"
readme = "README.md"
homepage = "https://sorairolake.github.io/hf/"
repository = "https://github.com/sorairolake/hf"
license = "Apache-2.0 OR MIT"
keywords = ["hidden"]
categories = ["command-line-utilities", "filesystem"]
include = ["/LICENSES", "/README.md", "/src"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hf"
required-features = ["application"]

[dependencies]
anyhow = { version = "1.0.81", optional = true }
clap = { version = "4.5.4", features = ["derive", "wrap_help"], optional = true }
clap_complete = { version = "4.5.2", optional = true }
clap_complete_nushell = { version = "4.5.1", optional = true }
log = { version = "0.4.21", optional = true }
simplelog = { version = "0.12.2", optional = true }
sysexits = { version = "0.7.12", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.54.0", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
tempfile = "3.10.1"

[features]
default = ["application"]
application = [
  "dep:anyhow",
  "dep:clap",
  "dep:clap_complete",
  "dep:clap_complete_nushell",
  "dep:log",
  "dep:simplelog",
  "dep:sysexits",
]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
