// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= hf-hide(1)
// Specify in UTC.
:docdate: 2024-06-28
:doctype: manpage
ifdef::revnumber[:mansource: hf {revnumber}]
ifndef::revnumber[:mansource: hf]
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

hf-hide - make files or directories invisible

== SYNOPSIS

*hf hide* [_OPTION_]... [_FILE_]...

== DESCRIPTION

This command makes files or directories invisible.

== POSITIONAL ARGUMENTS

_FILE_::

  Files or directories to hide.

== OPTIONS

*--log-level* _LEVEL_::

  The minimum log level to print.

  The possible values are:{blank}:::

    *OFF*::::

      Lowest log level.

    *ERROR*::::

      Error log level.

    *WARN*::::

      Warn log level.

    *INFO*::::

      Info log level. This is the default value.

    *DEBUG*::::

      Debug log level.

    *TRACE*::::

      Trace log level.

*-f*, *--force*::

  Actually hide files or directories.

*-n*, *--dry-run*::

  Don't actually hide anything, just show what would be done.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

== EXAMPLES

Make the given file invisible:{blank}::

  $ *hf hide -f data.txt*

Show what would be done:{blank}::

  $ *hf hide -n Cargo.toml src/*

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*hf*(1), *hf-show*(1), *hf-help*(1)
