// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= hf-help(1)
// Specify in UTC.
:docdate: 2024-03-27
:revnumber: 0.3.6
:doctype: manpage
:mansource: hf {revnumber}
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

hf-help - print the help for a command

== SYNOPSIS

*hf help* [_COMMAND_]

== DESCRIPTION

This command prints the help for a command.

This command is identical to any of the following:{blank}::

  $ *hf* [_COMMAND_] *-h*|*--help*

== POSITIONAL ARGUMENTS

_COMMAND_::

  Subcommand to print the help.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*hf*(1), *hf-hide*(1), *hf-show*(1)
