// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= hf-show(1)
// Specify in UTC.
:docdate: 2025-01-08
:revnumber: 0.3.8
:doctype: manpage
:mansource: hf {revnumber}
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]

== NAME

hf-show - make hidden files and directories visible

== SYNOPSIS

*hf show* [_OPTION_]... [_FILE_]...

== DESCRIPTION

This command makes hidden files and directories visible.

On Unix, this command renames the file to start with a character other than
`.`. On Windows, this command clears the hidden file attribute to the file.

When you run this command, you must specify either *-f* or *-n*. When *-n* is
specified, it just shows what would be done. When *-f* is specified, it
actually show hidden files.

== POSITIONAL ARGUMENTS

_FILE_::

  Hidden files and directories to show.

== OPTIONS

*--log-level* _LEVEL_::

  The minimum log level to print.

  The possible values are:{blank}:::

    *OFF*::::

      Lowest log level.

    *ERROR*::::

      Error log level.

    *WARN*::::

      Warn log level.

    *INFO*::::

      Info log level. This is the default value.

    *DEBUG*::::

      Debug log level.

    *TRACE*::::

      Trace log level.

*-f*, *--force*::

  Actually show hidden files and directories.

*-n*, *--dry-run*::

  Don't actually show anything, just show what would be done.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

== EXAMPLES

Make the given hidden file visible:{blank}::

  $ *hf show -f .data.txt*

Show what would be done:{blank}::

  $ *hf show -n .github/ .gitignore*

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]

== SEE ALSO

*hf*(1), *hf-hide*(1), *hf-help*(1)
