// SPDX-FileCopyrightText: 2022 Shun Sakai
//
// SPDX-License-Identifier: CC-BY-4.0

= hf(1)
// Specify in UTC.
:docdate: 2025-01-08
:revnumber: 0.3.8
:doctype: manpage
:mansource: hf {revnumber}
:manmanual: General Commands Manual
ifndef::site-gen-antora[:includedir: ./include]
:enwp-url: https://en.wikipedia.org
:enwp-article-url: {enwp-url}/wiki
:hidden-file-url: {enwp-article-url}/Hidden_file_and_hidden_directory

== NAME

hf - an utility for hidden files and directories

== SYNOPSIS

*{manname}* [_OPTION_]... _COMMAND_

== DESCRIPTION

*{manname}* is a command-line utility for
{hidden-file-url}[hidden files and directories].

== COMMANDS

*hf-hide*(1)::

  Make files and directories invisible.

*hf-show*(1)::

  Make hidden files and directories visible.

*hf-help*(1)::

  Print the help for a command.

== OPTIONS

*--log-level* _LEVEL_::

  The minimum log level to print.

  The possible values are:{blank}:::

    *OFF*::::

      Lowest log level.

    *ERROR*::::

      Error log level.

    *WARN*::::

      Warn log level.

    *INFO*::::

      Info log level. This is the default value.

    *DEBUG*::::

      Debug log level.

    *TRACE*::::

      Trace log level.

*-h*, *--help*::

  Print help message. The short flag (*-h*) will print a condensed help message
  while the long flag (*--help*) will print a detailed help message.

*-V*, *--version*::

  Print version number. The long flag (*--version*) will also print the
  copyright notice, the license notice and where to report bugs.

*--generate-completion* _SHELL_::

  Generate shell completion. The completion is output to standard output.

  The possible values are:{blank}:::

    *bash*::::

      Bash.

    *elvish*::::

      Elvish.

    *fish*::::

      fish.

    *nushell*::::

      Nushell.

    *powershell*::::

      PowerShell.

    *zsh*::::

      Zsh.

ifndef::site-gen-antora[include::{includedir}/section-exit-status.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-exit-status.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-notes.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-notes.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-reporting-bugs.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-reporting-bugs.adoc[]]

ifndef::site-gen-antora[include::{includedir}/section-copyright.adoc[]]
ifdef::site-gen-antora[include::partial$man/man1/include/section-copyright.adoc[]]
