//
// SPDX-License-Identifier: Apache-2.0 OR MIT
//
// Copyright (C) 2022 Shun Sakai
//

== OPTIONS

*-H*, *--hide*::
  Make files or directories invisible.
+
This option cannot be used with *--show*.

*-s*, *--show*::
  Make hidden files or directories visible.
+
This option cannot be used with *--hide*.

*-f*, *--force*::
  Make actual changes to files or directories.
+
This option cannot be used with *--dry-run*.

*-n*, *--dry-run*::
  Only show what would be done.
  This option prints a list of files to change.
+
This option cannot be used with *--force*.

*-q*, *--quiet*::
  Suppress log messages.
+
This option cannot be used with *--verbose*.

*-v*, *--verbose*::
  Verbose mode.
  This option can be specified multiple times to increase the log level.
+
This option cannot be used with *--quiet*.

*-h*, *--help*::
  Print help information.

*-V*, *--version*::
  Print version information.

*--generate-completion* _SHELL_::
  Generate shell completion.
  The completion is output to stdout.

  Possible values for this option are:{blank}:::

    * *bash*
    * *elvish*
    * *fish*
    * *powershell*
    * *zsh*
