name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  schedule:
      - cron: '0 0 * * *'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-20.04
            use-cross: true
          - target: x86_64-apple-darwin
            os: macos-11
          - target: x86_64-pc-windows-msvc
            os: windows-2022
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: 1.61.0 # MSRV
        target: ${{ matrix.target }}
        override: true
        profile: minimal
    - name: Cache build artifacts
      uses: Swatinem/rust-cache@v1.3.0
      with:
        key: ${{ matrix.target }}
    - name: Build a package
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --target ${{ matrix.target }}
        use-cross: ${{ matrix.use-cross }}
    - name: Run tests
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test
        args: --target ${{ matrix.target }}
        use-cross: ${{ matrix.use-cross }}

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt
    - name: Cache build artifacts
      uses: Swatinem/rust-cache@v1.3.0
    - name: Check code formatted
      uses: actions-rs/cargo@v1.0.1
      with:
        command: fmt
        args: -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: clippy
    - name: Cache build artifacts
      uses: Swatinem/rust-cache@v1.3.0
    - name: Check no lint warnings
      uses: actions-rs/cargo@v1.0.1
      with:
        command: clippy
        args: -- -D warnings
